export const books = [
  { id: 1, title: 'Laskar Pelangi', author: 'Andrea Hirata', year: 2005 },
  { id: 2, title: 'Bumi Manusia', author: 'Pramoedya Ananta Toer', year: 1980 },
  { id: 3, title: 'Cantik Itu Luka', author: 'Eka Kurniawan', year: 2002 },
  { id: 4, title: 'Negeri 5 Menara', author: 'Ahmad Fuadi', year: 2009 },
  { id: 5, title: 'Perahu Kertas', author: 'Dee Lestari', year: 2009 },
  { id: 6, title: 'Ronggeng Dukuh Paruk', author: 'Ahmad Tohari', year: 1982 },
  {
    id: 7,
    title: 'Tenggelamnya Kapal van der Wijck',
    author: 'Hamka',
    year: 1938,
  },
  { id: 8, title: 'Saman', author: 'Ayu Utami', year: 1998 },
  { id: 9, title: 'Pulang', author: 'Leila S. Chudori', year: 2012 },
  { id: 10, title: 'Gadis Kretek', author: 'Ratih Kumala', year: 2012 },
  {
    id: 11,
    title: 'Hujan Bulan Juni',
    author: 'Sapardi Djoko Damono',
    year: 1994,
  },
  {
    id: 12,
    title: 'Supernova: Ksatria, Puteri, dan Bintang Jatuh',
    author: 'Dee Lestari',
    year: 2001,
  },
  { id: 13, title: 'Sang Pemimpi', author: 'Andrea Hirata', year: 2006 },
  {
    id: 14,
    title: 'Anak Semua Bangsa',
    author: 'Pramoedya Ananta Toer',
    year: 1981,
  },
  { id: 15, title: 'Filosofi Kopi', author: 'Dee Lestari', year: 2006 },
  { id: 16, title: 'Amba', author: 'Laksmi Pamuntjak', year: 2012 },
  { id: 17, title: 'Entrok', author: 'Okky Madasari', year: 2010 },
  { id: 18, title: 'Madre', author: 'Dee Lestari', year: 2011 },
  { id: 19, title: 'Garis Waktu', author: 'Fiersa Besari', year: 2016 },
  { id: 20, title: 'Radikus Makankokus', author: 'Raditya Dika', year: 2007 },
]
